# Generated by Django 5.2 on 2025-06-25 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameShift', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Názov smeny môže obsahovať len písmená, čísla, medzery a pomlčky.', regex='^[A-Za-z0-9\\s\\-]+$')])),
                ('start_time', models.TimeField(max_length=4)),
                ('end_time', models.TimeField(max_length=4)),
                ('duration_time', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5, message='Trvanie musí byť aspoň 0.5 hodiny'), django.core.validators.MaxValueValidator(24.0, message='Trvanie nemôže byť viac ako 24 hodín')])),
            ],
        ),
    ]
