# Generated by Django 5.2 on 2025-06-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0004_changereason_plannedshifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeshift',
            name='nameShift',
            field=models.CharField(max_length=50),
        ),
    ]
