# Generated by Django 5.2 on 2025-07-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0005_alter_typeshift_nameshift'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
