# Generated by Django 5.2 on 2025-07-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0006_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedshifts',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
    ]
