# Generated by Django 5.2 on 2025-07-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0007_plannedshifts_transferred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedshifts',
            name='change_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
