# Generated by Django 5.2 on 2025-07-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0008_alter_plannedshifts_change_reason'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plannedshifts',
            unique_together={('user', 'date', 'custom_start', 'custom_end')},
        ),
    ]
