# Generated by Django 5.2 on 2025-07-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0009_alter_plannedshifts_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='exchanged_with',
            field=models.ForeignKey(blank=True, help_text='Pôvodná smena kolegu, ktorú zamestnanec prebral', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WorkTrackApi.plannedshifts'),
        ),
    ]
