# Generated by Django 5.2 on 2025-07-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0011_calendarday'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarday',
            name='holiday_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
