# Generated by Django 5.2 on 2025-07-09 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0012_calendarday_holiday_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='calendar_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='WorkTrackApi.calendarday'),
        ),
        migrations.AddField(
            model_name='plannedshifts',
            name='calendar_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_shifts', to='WorkTrackApi.calendarday'),
        ),
    ]
