# Generated by Django 5.2 on 2025-07-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0013_attendance_calendar_day_plannedshifts_calendar_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changereason',
            name='code',
        ),
        migrations.AddField(
            model_name='changereason',
            name='category',
            field=models.CharField(choices=[('absence', 'Neprítomnosť / zmena rozpisu'), ('cdr', 'Iná činnosť zamestnanca ')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='changereason',
            name='name',
            field=models.CharField(default='Dôvod nezadaný', max_length=255),
        ),
        migrations.AlterField(
            model_name='changereason',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
