# Generated by Django 5.2 on 2025-07-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0014_remove_changereason_code_changereason_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeshift',
            name='allow_variable_time',
            field=models.BooleanField(default=False, help_text='Ak je zapnuté, zamestnanec môže prísť a odísť kedykoľvek (napr. flexibilná smena).'),
        ),
        migrations.AlterField(
            model_name='changereason',
            name='category',
            field=models.CharField(choices=[('absence', 'Neprítomnosť / zmena rozpisu'), ('cdr', 'Iná činnosť zamestnanca ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plannedshifts',
            name='calendar_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_shifts', to='WorkTrackApi.changereason'),
        ),
        migrations.AlterField(
            model_name='plannedshifts',
            name='change_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_reason', to='WorkTrackApi.calendarday'),
        ),
        migrations.AlterField(
            model_name='typeshift',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='typeshift',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
