# Generated by Django 5.2 on 2025-07-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0015_typeshift_allow_variable_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedshifts',
            name='calendar_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_day', to='WorkTrackApi.calendarday'),
        ),
        migrations.AlterField(
            model_name='plannedshifts',
            name='change_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_reason', to='WorkTrackApi.changereason'),
        ),
    ]
