# Generated by Django 5.2 on 2025-07-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0016_alter_plannedshifts_calendar_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedshifts',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
