# Generated by Django 5.2 on 2025-07-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0017_plannedshifts_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='planned_shift',
            field=models.ForeignKey(blank=True, help_text='Vybraná plánovaná smena, z ktorej sa preberajú časy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_as_planned', to='WorkTrackApi.plannedshifts'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='exchanged_with',
            field=models.ForeignKey(blank=True, help_text='Pôvodná smena kolegu, ktorú zamestnanec prebral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_as_exchanged_with', to='WorkTrackApi.plannedshifts'),
        ),
    ]
