# Generated by Django 5.2 on 2025-07-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0018_attendance_planned_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedshifts',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
