# Generated by Django 5.2 on 2025-08-02 02:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0020_alter_attendance_options_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeshift',
            name='duration_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5'), message='Trvanie musí byť aspoň 0.5 hodiny'), django.core.validators.MaxValueValidator(Decimal('24.0'), message='Trvanie nemôže byť viac ako 24 hodín')]),
        ),
        migrations.AlterField(
            model_name='typeshift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typeshift',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
