# Generated by Django 5.2 on 2025-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0021_alter_typeshift_duration_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeshift',
            name='shortName',
            field=models.CharField(default='ds', max_length=2),
        ),
    ]
