# Generated by Django 5.2 on 2025-08-18 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0022_typeshift_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedshifts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_shifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
