# Generated by Django 5.2 on 2026-01-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0023_alter_plannedshifts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedshifts',
            name='calendar_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_calendar_day', to='WorkTrackApi.calendarday'),
        ),
    ]
