# Generated by Django 5.2 on 2026-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0024_alter_plannedshifts_calendar_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='initial_hours_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Počiatočný stav prenesených hodín (napr. +10.5 alebo -5.0) pri nástupe alebo štarte systému.', max_digits=6),
        ),
    ]
