# Generated by Django 5.2 on 2026-01-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0025_employees_initial_hours_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedshifts',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Čaká na schválenie'), ('approved', 'Schválené'), ('rejected', 'Zamietnuté')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='plannedshifts',
            name='manager_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
