# Generated by Django 5.2.3 on 2026-02-05 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTrackApi', '0026_plannedshifts_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedshifts',
            name='exchange_link',
            field=models.ForeignKey(blank=True, help_text='Odkaz na pôvodnú smenu pri výmene', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_linked_shifts', to='WorkTrackApi.plannedshifts'),
        ),
    ]
